#include <map>
#include <vector>
#include <string>
namespace resource {
	static std::map<int, std::vector<std::string>> mods{
		{0, {"Additional Ender Blocks","Cleverpanda714"}},
		{1, {"Advanced Generators", "bdew"}},
		{2, {"Aether II", "Gilded Games"}},
		{3, {"Animania", "Purpilicious_Cow, RazzleberryFox"}},
		{4, {"AppleSkin", "squeek"}},
		{5, {"Applied Energistics 2", "AlgorithmX2"}},
		{6, {"asielib", "Vexatos"}},
		{7, {"Atomic Science", "DarkGuardsman"}},
		{8, {"Baubles", "Azanor"}},
		{9, {"BD Lib", "bdew"}},
		{10, {"Better Foliage", "octarine-noise"}},
		{11, {"Bewitchment", "zabi94, Ingoleth, sunconure11"}},
		{12, {"BiblioCraft", "Joseph 'Nuchaz' Sinclair"}},
		{13, {"Biomes O' Plenty", "Forstride, TheAdubbz"}},
		{14, {"Blood Arsenal","Arcaratus"}},
		{15, {"Blood Magic", "WayofTime, TehNut"}},
		{16, {"Botania", "Vazkii"}},
		{17, {"Buildcraft", "SpaceToad, Buildcraft Team"}},
		{18, {"Carpenter's blocks", "Mineshopper"}},
		{19, {"Chisel", "tterrag, Drullkus, minecreatr"}},
		{20, {"Classic Combat", "WildBamaBoy, SheWolfDeadly"}},
		{21, {"CodeChickenLib", "ChickenBones, covers1624"}},
		{22, {"CoFH Core", "Team CoFH"}},
		{23, {"CoFH World", "Team CoFH"}},
		{24, {"CoFH Vanilla+ Satchels", "Team CoFH"}},
		{25, {"Compact Machines 3", "Davenonymous"}},
		{26, {"Compact Solar Arrays", "cpw"}},
		{27, {"Computronics", "asiekierka, Techokami, Vexatos"}},
		{28, {"CoroUtil Library", "Corosus"}},
		{29, {"CraftStudio API", "Leviathan Studios"}},
		{30, {"CreativeCore", "CreativeMD"}},
		{31, {"CreativeCoreDummy" , "CreativeMD"}},
		{32, {"CTM", "tterrag, Drullkus, minecreatr"}},
		{33, {"Cucumber Library", "BlakeBr0"}},
		{34, {"Decocraft", "RazzleberryFox"}},
		{35, {"Dimensional Doors", "StevenRS11"}},
		{36, {"DrZhark's CustomSpawner", "DrZhark"}},
		{37, {"DrZhark's Mo'Creatures", "DrZhark"}},
		{38, {"Dynamic Surroundings", "OreCruncher, Abastro"}},
		{39, {"Ender IO", "tterrag, CrazyPants"}},
		{40, {"EnderCore", "tterrag, CrazyPants"}},
		{41, {"Energy Converters", "xalcon"}},
		{42, {"Equivalent Additions", "TehenoPengin, Zeitheron"}},
		{43, {"Exotic Birds", "Pavocado"}},
		{44, {"Expanded Equivalence", "Zeitheron"}},
		{45, {"Extended Mod Config", "Corosus"}},
		{46, {"Extended Renderer", "Corosus"}},
		{47, {"Extra Planets", "MJRLegends"}},
		{48, {"Extra Utilities 2", "RWTema"}},
		{49, {"Flux Networks", "Sonar Sonic, BloCamLimb"}},
		{50, {"FoamFix", "asiekierka"}},
		{51, {"FoamFixCore", "asie"}},
		{52, {"Forestry", "SirSengir, mezz"}},
		{53, {"Forge Microblocks", "ChickenBones"}},
		{54, {"Forge Mod Loader", "cpw, LexManos"}},
		{55, {"Forge Multipart CBE", "Chicken-Bones"}},
		{56, {"Fossils and Archeology Revival", "Fossils and Archeology Team"}},
		{57, {"Galacticraft Core", "micdoodle8,"}},
		{58, {"Galacticraft Planets", "micdoodle8"}},
		{59, {"GasConduits", "pupnewfster"}},
		{60, {"Growthcraft", "Alatyami, Avatair, Kisutora"}},
		{61, {"Guide-API", "Tombenpotter, TehNut"}},
		{62, {"Hammer Core", "Zeitheron"}},
		{63, {"Hats", "iChun"}},
		{64, {"HatStand", "iChun"}},
		{65, {"ICBM-Classic", "Calclavia, DarkGuardsman"}},
		{66, {"iChunUtil", "iChun"}},
		{67, {"Immersive Engineering", "BluSunrize, Damien A.W. Hazard"}},
		{68, {"IndustrialCraft 2", "The IndustrialCraft team"}},
		{69, {"Inventory Tweaks", "Jimeo Wan, Kobata"}},
		{70, {"Iron Chest", "cpw"}},
		{71, {"ItemPhysic", "CreativeMD"}},
		{72, {"Just Enough HarvestCraft", "mrapplexz"}},
		{73, {"Just Enough Items", "mezz"}},
		{74, {"JustEnoughIDs", "Runemoro, ZombieHDGaming"}},
		{75, {"Leather Works", "Cleverpanda714"}},
		{76, {"LLibrary", "iLexiconn, gegy1000"}},
		{77, {"Localized Weather & Storms", "Corosus"}},
		{78, {"Macaw's Bridges", "Sketch Macaw"}},
		{79, {"Macaw's Roofs", "Sketch Macaw"}},
		{80, {"MachineMuse's Modular Powersuits", "MachineMuse"}},
		{81, {"MagicBees", "MysteriousAges"}},
		{82, {"Mantle", "boni, progWML6, Alexbegt"}},
		{83, {"Mekanism", "aidancbrady"}},
		{84, {"Mekanism: Generators", "aidancbrady"}},
		{85, {"Mekanism: Tools", "aidancbrady"}},
		{86, {"Metallurgy 4: Reforged", "Davoleo, ItHurtsLikeHell"}},
		{87, {"Micdoodle8 Core", "Micdoodle8"}},
		{88, {"Millenaire", "Kinniken"}},
		{89, {"Minecraft Coder Pack", "MCP team"}},
		{90, {"Minecraft Comes Alive", "WildBamaBoy"}},
		{91, {"Minecraft Forge", "LexManos, cpw, fry"}},
		{92, {"Minecraft Multipart Plugin", "ChickenBones"}},
		{93, {"MJRLegends Lib", "MJRLegends"}},
		{94, {"Modular ForceField System", "nekosune"}},
		{95, {"More Planets", "SteveKunG, PloyiinGz"}},
		{96, {"More Planets Extras", "MJRLegends"}},
		{97, {"Morph", "Corosus"}},
		{98, {"Mouse Tweaks", "YaLTeR"}},
		{99, {"MrCrayfish's Furniture Mod", "MrCrayfish"}},
		{100, {"MrTJPCore", "MrTJP"}},
		{101, {"Mystcraft", "XCompWiz"}},
		{102, {"Mystical Agriculture", "BlakeBr0"}},
		{103, {"Natura", "mDiyo, Slime Knights"}},
		{104, {"No Night Vision Flashing", "Team CoFH"}},
		{105, {"No Recipe Book", "Luwin"}},
		{106, {"Not Enough Items", "ChickenBones"}},
		{107, {"Numina", "MachineMuse"}},
		{108, {"OnlinePictureFrame", "CreativeMD"}},
		{109, {"OpenBlocks", "Mikee, NeverCast, boq, Lyqyd"}},
		{110, {"OpenComputers", "Sangar, Vexatos, payonel, magik6k, Lord Joda"}},
		{111, {"OpenComputers (Core)", "Sangar"}},
		{112, {"OpenEye", "boq, Mikee"}},
		{113, {"OpenModsLib", "Mikee, NeverCast, boq, Lyqyd"}},
		{114, {"OpenModsLib Core", "Mikee, NeverCast, boq"}},
		{115, {"OrbisLib", "Gilded Games"}},
		{116, {"OreLib Support Library", "OreCruncher"}},
		{117, {"Pam's HarvestCraft", "Pamela Collins"}},
		{118, {"Patchouli", "Vazkii"}},
		{119, {"Performant Mod", "SomeAddons"}},
		{120, {"Phosphor Lighting Engine", "Angeline"}},
		{121, {"Planet Progression", "MJRLegends"}},
		{122, {"PortalGun", "Corosus"}},
		{123, {"ProjectE", "sinkillerj, Moze_Intel"}},
		{124, {"ProjectRed", "MrTJP, ChickenBones, covers1624"}},
		{125, {"ProjectRed compat", "MrTJP, ChickenBones, covers1624"}},
		{126, {"ptrmodellib", "RazzleberryFox"}},
		{127, {"Railcraft", "CovertJaguar"}},
		{128, {"Redstone Arsenal", "CoFH Core"}},
		{129, {"Redstone Flux", "CoFH Core"}},
		{130, {"Rustic", "the-realest-stu"}},
		{131, {"Secret Rooms 5", "Wyn Prince"}},
		{132, {"Secret Rooms Hooks", "Wyn Prince"}},
		{133, {"Serene Seasons", "Adubbz, Forstride"}},
		{134, {"Shadowfacts' Forgelin", "shadowfacts"}},
		{135, {"Signpost", "Gollorum"}},
		{136, {"SpaceAmbient", "BlesseNtumble"}},
		{137, {"Stellar Fluid Conduits", "Tfarecnim"}},
		{138, {"SteveKunG's Lib", "SteveKunG"}},
		{139, {"Sync", "Corosus"}},
		{140, {"TallGates", "Gory_Moon"}},
		{141, {"Thaumcraft", "Azanor"}},
		{142, {"Thaumic Energistics", "Nividica, BrockWS"}},
		{143, {"Thaumic Tinkerer", "nekosune"}},
		{144, {"The Twilight Forest", "Benimatic"}},
		{145, {"Thermal Cultivation", "Team CoFH"}},
		{146, {"Thermal Dynamics", "Team CoFH"}},
		{147, {"Thermal Expansion", "Team CoFH"}},
		{148, {"Thermal Foundation", "Team CoFH"}},
		{149, {"Thermal Innovation", "Team CoFH"}},
		{150, {"Tinkers' Construct", "boni, KnightMiner"}},
		{151, {"Tropicraft", "Cojomax99, Corosus, tterrag"}},
		{152, {"VoxelMap", "MamiyaOtaru"}},
		{153, {"Waila", "ProfMobius, TehNut"}},
		{154, {"What Are We Looking At", "Darkhax"}}
	};
}